# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: readmin
  password: shikapippi
  host: localhost

development:
  <<: *default
  database: review_dev

test:
  <<: *default
  database: review_test

production:
  <<: *default
  database: review_pro
